import {ENGLISH, TimeI18N} from "Frontend/i18n/TimeI18N";

// TODO This function has practically been generated by an AI, so it needs to be tested
export function formatPastDate(date: Date, i18n: TimeI18N = ENGLISH): string {
    const now = new Date();
    const diff = Math.abs(now.getTime() - date.getTime()) / 1000;
    if (diff < 60) { // Less than a minute
        return i18n.justNow;
    } else if (diff < 120) { // Less than two minutes
        return i18n.minuteAgo;
    } else if (diff < 3600) { // Less than an hour
        return i18n.minutesAgo.replace("{0}", Math.floor(diff / 60).toString(10));
    } else if (diff < 7200) { // Less than two hours
        return i18n.hourAgo;
    } else if (diff < 86400) { // Less than a day (24 hours)
        return i18n.hoursAgo.replace("{0}", Math.floor(diff / 3600).toString(10));
    } else if (diff < 172800) { // Less than two days
        return i18n.dayAgo;
    } else if (diff < 604800) { // Less than a week (7 days)
        return i18n.daysAgo.replace("{0}", Math.floor(diff / 86400).toString(10));
    } else if (diff < 1209600) { // Less than two weeks
        return i18n.weekAgo;
    } else if (diff < 2592000) { // Less than a month (30 days)
        return i18n.weeksAgo.replace("{0}", Math.floor(diff / 604800).toString(10));
    } else if (diff < 5184000) { // Less than two months
        return i18n.monthAgo;
    } else if (diff < 31536000) { // Less than a year (365 days)
        return i18n.monthsAgo.replace("{0}", Math.floor(diff / 2592000).toString(10));
    } else if (diff < 63072000) { // Less than two years
        return i18n.yearAgo;
    } else {
        return i18n.yearsAgo.replace("{0}", Math.floor(diff / 31536000).toString(10));
    }
}